title: Aditya Sawant
theme: jekyll-theme-cayman

baseurl: "/portfolio"
# Links
links:
  - name: Resume
    url: https://drive.google.com/file/d/10EuQHWXmkuHVNgbLgyqj_151hh9IZXis/view?usp=drive_link
    icon: fab fa-google-drive
  - name: LinkedIn
    url: https://www.linkedin.com/in/adityassawant/
    icon: fab fa-linkedin
  - name: GitHub
    url: https://github.com/290491
    icon: fab fa-github
